# Generated by Django 4.0 on 2022-04-04 09:53

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Quote',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField(max_length=2000, verbose_name='Текст')),
                ('user_name', models.CharField(max_length=256, verbose_name='Имя добавившего')),
                ('email', models.EmailField(max_length=254, verbose_name='Эл. адрес')),
                ('rating', models.PositiveIntegerField(default=0, verbose_name='Рейтинг')),
                ('status', models.CharField(choices=[('new', 'Новая'), ('status', 'Модерированная')], default='new', max_length=24, verbose_name='Статус')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
            ],
        ),
    ]
